# CyberOS tmux
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",foot:RGB"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 50000
set -sg escape-time 10
set -g focus-events on

# prefix: Ctrl-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind r source-file ~/.config/tmux/tmux.conf \; display "reloaded"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
setw -g mode-keys vi

# theme
set -g status-position top
set -g status-style "bg=#11161F,fg=#E6EDF3"
set -g status-left "#[bg=#00FF9C,fg=#0A0E14,bold]  #S #[bg=#11161F] "
set -g status-right "#[fg=#00D4FF]%H:%M #[fg=#6B7A90]%d %b "
setw -g window-status-format "#[fg=#6B7A90] #I:#W "
setw -g window-status-current-format "#[fg=#00FF9C,bold] #I:#W "
set -g pane-border-style "fg=#1F2937"
set -g pane-active-border-style "fg=#00FF9C"
set -g message-style "bg=#00FF9C,fg=#0A0E14"
