# CyberOS tmux
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",foot:RGB"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 50000
set -sg escape-time 10
set -g focus-events on

# prefix: Ctrl-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind r source-file ~/.config/tmux/tmux.conf \; display "reloaded"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
setw -g mode-keys vi

# theme
set -g status-position top
set -g status-style "bg=#004C23,fg=#ECF1EE"
set -g status-left "#[bg=#FFCB06,fg=#0B1610,bold]  #S #[bg=#004C23] "
set -g status-right "#[fg=#3DBB6E]%H:%M #[fg=#7A8F82]%d %b "
setw -g window-status-format "#[fg=#7A8F82] #I:#W "
setw -g window-status-current-format "#[fg=#FFCB06,bold] #I:#W "
set -g pane-border-style "fg=#1E3A2A"
set -g pane-active-border-style "fg=#FFCB06"
set -g message-style "bg=#FFCB06,fg=#0B1610"
