-- Cyber Department colourscheme (built on the bundled 'habamax' base)
vim.cmd.colorscheme("habamax")
local hi = function(g, s) vim.api.nvim_set_hl(0, g, s) end
hi("Normal",       { fg = "#ECF1EE", bg = "#0B1610" })
hi("NormalFloat",  { fg = "#ECF1EE", bg = "#12241A" })
hi("LineNr",       { fg = "#4A5E52" })
hi("CursorLineNr", { fg = "#FFCB06", bold = true })
hi("Comment",      { fg = "#7A8F82", italic = true })
hi("String",       { fg = "#FFCB06" })
hi("Function",     { fg = "#3DBB6E" })
hi("Keyword",      { fg = "#C41118" })
hi("Type",         { fg = "#8FD9A8" })
hi("Constant",     { fg = "#FFB600" })
hi("Visual",       { bg = "#1E3A2A" })
hi("StatusLine",   { fg = "#FFCB06", bg = "#004C23", bold = true })
hi("StatusLineNC", { fg = "#7A8F82", bg = "#12241A" })
hi("Pmenu",        { fg = "#ECF1EE", bg = "#12241A" })
hi("PmenuSel",     { fg = "#0B1610", bg = "#FFCB06" })
hi("Search",       { fg = "#0B1610", bg = "#FFB600" })
hi("VertSplit",    { fg = "#1E3A2A" })
hi("WinSeparator", { fg = "#1E3A2A" })
