-- Generated by cyberos-theme (light)
return {
  bg = "#F5F5F5", surface = "#E1DFE1", fg = "#1D1D1F", muted = "#6E6E73",
  accent = "#00CA4E", accent2 = "#FFBD44", alert = "#FF605C",
  border = "#C0BFC0", sel = "#E1DFE1", blue = "#0A84FF", cyan = "#5AC8FA",
  dark = false,
}
