-- Cyber Department colourscheme (built on the bundled 'habamax' base)
vim.cmd.colorscheme("habamax")
local hi = function(g, s) vim.api.nvim_set_hl(0, g, s) end
hi("Normal",       { fg = "#E6EDF3", bg = "#0A0E14" })
hi("NormalFloat",  { fg = "#E6EDF3", bg = "#11161F" })
hi("LineNr",       { fg = "#4B5563" })
hi("CursorLineNr", { fg = "#00FF9C", bold = true })
hi("Comment",      { fg = "#6B7A90", italic = true })
hi("String",       { fg = "#00FF9C" })
hi("Function",     { fg = "#00D4FF" })
hi("Keyword",      { fg = "#FF2A6D" })
hi("Type",         { fg = "#BD93F9" })
hi("Constant",     { fg = "#F5D90A" })
hi("Visual",       { bg = "#1F2937" })
hi("StatusLine",   { fg = "#0A0E14", bg = "#00FF9C", bold = true })
hi("StatusLineNC", { fg = "#6B7A90", bg = "#11161F" })
hi("Pmenu",        { fg = "#E6EDF3", bg = "#11161F" })
hi("PmenuSel",     { fg = "#0A0E14", bg = "#00FF9C" })
hi("Search",       { fg = "#0A0E14", bg = "#F5D90A" })
hi("VertSplit",    { fg = "#1F2937" })
hi("WinSeparator", { fg = "#1F2937" })
