# CyberOS foot config
font=JetBrainsMono Nerd Font:size=11
pad=10x10
dpi-aware=no

[scrollback]
lines=10000

[cursor]
style=beam
blink=yes

[colors-dark]
alpha=0.80
background=0B1610
foreground=ECF1EE
regular0=0B1610
regular1=C41118
regular2=FFCB06
regular3=FFB600
regular4=6A91A9
regular5=8FD9A8
regular6=4E9E8C
regular7=C9D1D9
bright0=4A5E52
bright1=E8434A
bright2=6FD693
bright3=FFD84D
bright4=8FB3C8
bright5=B5EAC8
bright6=7FC4B4
bright7=FFFFFF
selection-background=1E3A2A
selection-foreground=FFCB06
