# CyberOS foot config
font=JetBrainsMono Nerd Font:size=11
pad=10x10
dpi-aware=no

[scrollback]
lines=10000

[cursor]
style=beam
blink=yes

[colors]
alpha=0.94
background=0A0E14
foreground=E6EDF3
regular0=0A0E14
regular1=FF2A6D
regular2=00FF9C
regular3=F5D90A
regular4=00D4FF
regular5=BD93F9
regular6=05FFA1
regular7=C9D1D9
bright0=4B5563
bright1=FF5C8A
bright2=5CFFC0
bright3=FFE66D
bright4=5CE1FF
bright5=D6ACFF
bright6=7DFFD1
bright7=FFFFFF
selection-background=1F2937
selection-foreground=00FF9C
