#!/usr/bin/env bash
# ============================================================================
#  CyberOS ISO builder
#    1. builds the AUR packages listed in aur/packages.txt into repo/ (as your user)
#    2. runs mkarchiso (as root) with profile/  →  out/cyberos-YYYY.MM.DD-x86_64.iso
#
#  Editions:  --edition base  (default, <= 2 GiB, fits a GitHub release asset)
#             --edition lab   (adds the security-lab toolset, offline classroom USBs)
#
#  Requirements (on an Arch host):  sudo pacman -S archiso base-devel git
#  Packet Tracer: drop CiscoPacketTracer_*_Ubuntu_64bit.deb (from netacad.com) into aur/
# ============================================================================
# `set -u` leaks into bats and breaks its internals when this file is sourced by
# the test suite, so it applies only when build.sh is actually executed.
if [[ ${BASH_SOURCE[0]} == "${0}" ]]; then
  set -euo pipefail
fi
ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO="$ROOT/repo"; WORK="$ROOT/work"; OUT="$ROOT/out"; PROFILE="$ROOT/profile"

# cyberos-base must fit GitHub's 2 GiB release-asset cap, or it cannot be
# distributed through the repository's own release page.
BASE_SIZE_BUDGET=$(( 2 * 1024 * 1024 * 1024 ))

msg() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
die() { echo "ERROR: $*" >&2; exit 1; }

# compose_packages <edition> <base-file> <lab-file> <out-file>
#
# Both editions come from one profile: the difference is which lists are
# concatenated. Two profiles would drift, and the drift would only show up on a
# student's machine.
compose_packages() {
  local edition=$1 base=$2 lab=$3 out=$4
  case $edition in
    base|lab) ;;
    *) printf 'unknown edition: %s (want base or lab)\n' "$edition" >&2; return 1 ;;
  esac
  {
    printf '# GENERATED by build.sh --edition %s. Do not edit.\n' "$edition"
    printf '# Edit %s' "$(basename "$base")"
    [[ $edition == lab ]] && printf ' or %s' "$(basename "$lab")"
    printf ' instead.\n\n'
    cat "$base"
    if [[ $edition == lab ]]; then printf '\n'; cat "$lab"; fi
  } >"$out"
}

# assert_iso_size <iso> <max-bytes>
assert_iso_size() {
  local iso=$1 max=$2 actual
  actual=$(stat -c %s "$iso")
  if (( actual > max )); then
    printf 'ISO is %s MiB, over the %s MiB budget.\n' \
      $(( actual / 1024 / 1024 )) $(( max / 1024 / 1024 )) >&2
    printf 'cyberos-base must fit GitHub 2 GiB release-asset cap; move packages to packages.lab.x86_64.\n' >&2
    return 1
  fi
  printf 'ISO size %s MiB, within the %s MiB budget.\n' \
    $(( actual / 1024 / 1024 )) $(( max / 1024 / 1024 ))
}

# Everything below this builds an ISO. Stop here when sourced for tests.
if [[ -n ${BUILD_LIB_ONLY:-} ]]; then
  return 0 2>/dev/null || exit 0
fi

SKIP_AUR=0; ONLY_AUR=0; EDITION=base
while [[ $# -gt 0 ]]; do
  case $1 in
    --skip-aur) SKIP_AUR=1; shift;;
    --only-aur) ONLY_AUR=1; shift;;
    --clean)    sudo rm -rf "$WORK"; shift;;
    --edition)  EDITION=${2:-}; shift 2;;
    -h|--help)  sed -n '2,12p' "$0"; exit 0;;
    *) die "unknown option $1";;
  esac
done

# Validate the edition now, not inside compose_packages: that runs after the AUR
# build, and a typo should not cost half an hour before it is reported.
case $EDITION in base|lab) ;; *) die "--edition must be base or lab (got '$EDITION')";; esac

[[ $EUID -ne 0 ]] || die "run build.sh as a normal user; it calls sudo where needed"
command -v mkarchiso >/dev/null || die "archiso not installed:  sudo pacman -S archiso"
command -v makepkg   >/dev/null || die "base-devel not installed: sudo pacman -S base-devel git"

# ------------------------------------------------------------------ 1. AUR
if [[ $SKIP_AUR -eq 0 ]]; then
  mkdir -p "$REPO" "$WORK/aur"
  while read -r pkg; do
    [[ -z $pkg || $pkg == \#* ]] && continue
    msg "AUR: $pkg"
    d="$WORK/aur/$pkg"
    if [[ -f $ROOT/aur/$pkg/PKGBUILD ]]; then
      mkdir -p "$d"; cp -f "$ROOT/aur/$pkg"/* "$d/"          # local PKGBUILD
    elif [[ -d $d/.git ]]; then
      # makepkg rewrites pkgver= in a VCS PKGBUILD, which leaves the clone dirty,
      # and `git pull` then refuses -- on a rebase-by-default config it refuses
      # outright. This clone is a disposable build cache, so take upstream's copy
      # rather than trying to merge into it. Untracked src/ and pkg/ are left
      # alone so makepkg can reuse them.
      git -C "$d" fetch -q origin
      git -C "$d" reset --hard -q FETCH_HEAD
    else
      git clone -q "https://aur.archlinux.org/$pkg.git" "$d"
    fi
    if [[ $pkg == packettracer ]]; then
      deb=$(ls "$ROOT"/aur/CiscoPacketTracer_*_Ubuntu_64bit.deb 2>/dev/null | head -1 || true)
      [[ -n $deb ]] || die "Packet Tracer: put CiscoPacketTracer_*_Ubuntu_64bit.deb from https://www.netacad.com into $ROOT/aur/"
      cp -f "$deb" "$d/"
      # Cisco re-releases the same version with different checksums; trust our local copy.
      (cd "$d" && updpkgsums >/dev/null 2>&1 || true)
    fi
    (cd "$d" && makepkg -sf --noconfirm --needed)
    cp -f "$d"/*.pkg.tar.zst "$REPO/"
  done < "$ROOT/aur/packages.txt"
  msg "Creating local repo"
  rm -f "$REPO"/cyberos.db* "$REPO"/cyberos.files*
  repo-add -q "$REPO/cyberos.db.tar.gz" "$REPO"/*.pkg.tar.zst
fi
[[ $ONLY_AUR -eq 1 ]] && exit 0

[[ -f $REPO/cyberos.db ]] || die "repo/ is empty — run without --skip-aur first"

# ------------------------------------------------------------------ 2. ISO
msg "Generating profile/pacman.conf"
sed "s|@REPO_DIR@|$REPO|" "$PROFILE/pacman.conf.in" > "$PROFILE/pacman.conf"

msg "Composing the $EDITION package list"
compose_packages "$EDITION" \
  "$PROFILE/packages.base.x86_64" "$PROFILE/packages.lab.x86_64" \
  "$PROFILE/packages.x86_64" || die "could not compose the package list"
printf '   %s packages\n' "$(grep -cv '^#\|^$' "$PROFILE/packages.x86_64")"

msg "Building ISO with mkarchiso (needs root)"
mkdir -p "$OUT" "$WORK"
LOG="$WORK/build.log"

# A stale work dir from a previous package set makes mkarchiso fail in ways that
# look like a profile bug. It is a scratch dir, so start clean.
if [[ -d $WORK/iso ]]; then
  msg "Removing the previous work directory"
  sudo rm -rf "$WORK/iso"
fi

# Tee to a log: without one, a failed build leaves nothing to read afterwards
# but scrollback.
echo "   logging to $LOG"
set -o pipefail
if ! sudo mkarchiso -v -w "$WORK/iso" -o "$OUT" "$PROFILE" 2>&1 | tee "$LOG"; then
  echo
  die "mkarchiso failed. Last 20 lines of $LOG:
$(tail -20 "$LOG")"
fi
sudo chown "$USER:$USER" "$OUT"/*.iso
msg "ISO ready:"; ls -lh "$OUT"/*.iso
ISO=$(ls -t "$OUT"/*.iso | head -1)
if [[ $EDITION == base ]]; then
  assert_iso_size "$ISO" "$BASE_SIZE_BUDGET" \
    || die "base edition is over budget; build --edition lab for the full toolset"
fi
echo "Test it:  ./test-vm.sh $ISO"
