pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// CyberOS palette. Generated by cyberos-theme into theme.json and watched, so
// Super+Shift+T re-themes the shell live. Colours are defined THERE, not here:
// the object below is only a fallback so a missing or broken theme.json
// degrades to a usable dark shell instead of an invisible one.
Singleton {
    id: root

    property var t: fallback
    readonly property var fallback: ({
        mode: "dark", bg: "#1D1D1F", surface: "#2B2B2D", fg: "#F5F5F5",
        muted: "#C0BFC0", accent: "#00CA4E", accent2: "#FFBD44",
        alert: "#FF605C", border: "#3A3A3C", sel: "#3A3A3C", barAlpha: 0.88
    })

    readonly property color bg: t.bg
    readonly property color surface: t.surface
    readonly property color fg: t.fg
    readonly property color muted: t.muted
    readonly property color accent: t.accent
    readonly property color accent2: t.accent2
    readonly property color alert: t.alert
    readonly property color border: t.border
    readonly property color sel: t.sel
    readonly property string mode: t.mode
    readonly property real barAlpha: t.barAlpha
    readonly property bool dark: mode === "dark"

    readonly property string fontFamily: "JetBrainsMono Nerd Font"
    readonly property int fontSize: 13
    readonly property int barHeight: 30
    readonly property int radius: 14

    FileView {
        path: Quickshell.env("XDG_CONFIG_HOME") !== ""
            ? Quickshell.env("XDG_CONFIG_HOME") + "/quickshell/theme.json"
            : Quickshell.env("HOME") + "/.config/quickshell/theme.json"
        watchChanges: true
        onTextChanged: {
            try {
                const parsed = JSON.parse(text());
                if (parsed.bg !== undefined) root.t = parsed;
            } catch (e) { /* keep the last good palette */ }
        }
        onLoadFailed: root.t = root.fallback
    }
}
